### ISSUE TITLE
Understanding the functionality of this service and all its references

### ISSUE THREAD

**Issue by travula** [DeviPrasad/sammati#1]
https://docs.google.com/presentation/d/1q9CgczFVR3saSqQMw_2Y3IHeYaa2Yn4lhfPBx8PTXAQ/edit?usp=sharing

where does the functionality provided by sammati fit in the above presentation?

Thanks

**Comment by DeviPrasad** [comment]
Thanks for asking!
"Dhaarana" is the spiritual inspiration for "Sammati". It is my desire to build a full-fledged P2P Lending system for impactful lending. Technologies like account aggregator are a crucial piece in the tech stack. This is more of an experiment at the moment.
