### ISSUE TITLE
Building Sammati

### ISSUE THREAD

**Issue by travula** [DeviPrasad/sammati#3]
> [travula:] ls
> Cargo.toml  docs  LICENSE  misc  mock  README.md  src
> [travula:] cargo build
>     Updating crates.io index
> error: failed to get `dull` as a dependency of package `sammati v0.0.1 (/home/travula/projects/dhaarana/sammati)`
> 
> Caused by:
>   failed to load source for dependency `dull`
> 
> Caused by:
>   Unable to update /home/travula/projects/dull/jwtse/rust/dull
> 
> Caused by:
>   failed to read `/home/travula/projects/dull/jwtse/rust/dull/Cargo.toml`
> 
> Caused by:
>   No such file or directory (os error 2)
> [travula:] pwd
> /home/travula/projects/dhaarana/sammati
> [travula:] 
>

**Comment by DeviPrasad** [comment]
Aah! I see. 
There's a dependency on cryptography library 
I shall update the workspace to include reference to 'dull'.
